version: '3.1'

services:
  web:
    image: odoo:16
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
